"""Per-step metrics and the final solution artifact imposed by the
assignment."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

__all__ = ["SolutionOutput", "StepMetrics"]


class StepMetrics(BaseModel):
    """Record the metrics of a single LLM-generate / sandbox-execute
    cycle."""

    step: int = Field(..., description="1-indexed iteration number.")
    input_tokens: int = Field(
        ..., description="Tokens sent to the LLM for this step."
    )
    output_tokens: int = Field(
        ..., description="Tokens generated by the LLM for this step."
    )
    request_time_ms: float = Field(
        ...,
        description="Wall-clock time of the LLM API call, in "
        "milliseconds.",
    )
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    api_url: str = Field(
        default="", description="Base URL of the LLM API endpoint."
    )
    model_name: str = Field(
        default="", description="Model identifier used for this step."
    )
    llm_output: str = Field(
        default="",
        description="Raw text generated by the LLM before code "
        "extraction.",
    )
    sandbox_input: str = Field(
        default="",
        description="Python code sent to the sandbox for execution.",
    )
    sandbox_output: str = Field(
        default="",
        description="Sandbox execution result (stdout/stderr/error).",
    )
    retries: int = Field(
        default=0,
        description="Number of LLM API retries before success.",
    )


class SolutionOutput(BaseModel):
    """Hold the final artifact an agent must write to solution.json."""

    task_id: str = Field(
        ...,
        description="MBPP task_id (as string) or SWE-bench "
        "instance_id.",
    )
    benchmark: str = Field(
        ..., description="Benchmark type: 'mbpp' or 'swebench'."
    )
    success: bool = Field(
        ..., description="Whether the agent believes it solved the task."
    )
    solution: str = Field(
        ...,
        description="MBPP: function code. SWE-bench: git patch (diff).",
    )
    iterations: int = Field(
        ..., description="Number of agent loop iterations used."
    )
    total_requests: int = Field(
        ...,
        description="Total LLM API requests made, including retries.",
    )
    total_input_tokens: int = Field(
        ..., description="Sum of input_tokens across all steps."
    )
    total_output_tokens: int = Field(
        ..., description="Sum of output_tokens across all steps."
    )
    total_time_seconds: float = Field(
        ..., description="Wall-clock time from start to finish."
    )
    steps: list[StepMetrics] = Field(
        default_factory=list, description="Per-step metrics."
    )
    system_prompt: str = Field(
        default="", description="Full system prompt sent to the LLM."
    )
    error: str | None = Field(
        default=None, description="Error message if the agent failed."
    )
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    stop_reason: str = Field(
        default="solved",
        description="Reason the agent stopped.",
    )
